#!/usr/bin/env python3
"""
Generate Unicode→GB2312 sorted lookup table for binary search on STM32.

For all GB2312 Chinese characters (0xB0A1 through 0xF7FE),
creates two parallel C arrays sorted by Unicode code point:
  - unicode_sorted[]: sorted Unicode code points (for binary search)
  - gb2312_index_sorted[]: corresponding GB2312 indexes (for font lookup)

Usage:
    python generate_unicode_table.py --output unicode_gb2312_table.inc
"""

import sys

ZONE_START = 0xB0
ZONE_END   = 0xF7
CHAR_START = 0xA1
CHAR_END   = 0xFE
CHARS_PER_ZONE = 94


def generate_table():
    entries = []

    for zone in range(ZONE_START, ZONE_END + 1):
        gb_h = zone
        for bit in range(CHAR_START, CHAR_END + 1):
            gb_l = bit
            gb_bytes = bytes([gb_h, gb_l])
            try:
                char = gb_bytes.decode('gb2312')
                unicode_cp = ord(char)
                gb_index = (zone - ZONE_START) * CHARS_PER_ZONE + (bit - CHAR_START)
                entries.append((unicode_cp, gb_index))
            except (UnicodeDecodeError, LookupError):
                continue

    entries.sort(key=lambda x: x[0])
    return entries


def write_c_file(entries, output_path=None):
    lines = []
    lines.append('/*')
    lines.append(' * Unicode→GB2312 sorted lookup tables for binary search.')
    lines.append(f' * {len(entries)} entries, sorted by Unicode code point.')
    lines.append(' * Generated by tools/generate_unicode_table.py')
    lines.append(' *')
    lines.append(' * unicode_sorted[]:    sorted Unicode values (binary search target)')
    lines.append(' * gb2312_index_sorted[]: parallel GB2312 index (0~6767) for font lookup')
    lines.append(' */')
    lines.append('')
    lines.append(f'#define UNICODE_TABLE_SIZE  {len(entries)}U')
    lines.append('')

    unicode_vals = [e[0] for e in entries]
    gb2312_vals  = [e[1] for e in entries]

    lines.append('/* Sorted Unicode code points for GB2312 characters */')
    lines.append('static const uint16_t unicode_sorted[UNICODE_TABLE_SIZE] = {')
    for i in range(0, len(unicode_vals), 8):
        chunk = unicode_vals[i:i+8]
        hex_str = ', '.join(f'0x{cp:04X}' for cp in chunk)
        lines.append(f'    {hex_str},')
    # Remove trailing comma from last line
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};')
    lines.append('')

    lines.append('/* Parallel GB2312 indexes corresponding to unicode_sorted[] */')
    lines.append('static const uint16_t gb2312_index_sorted[UNICODE_TABLE_SIZE] = {')
    for i in range(0, len(gb2312_vals), 8):
        chunk = gb2312_vals[i:i+8]
        hex_str = ', '.join(f'{idx:5d}' for idx in chunk)
        lines.append(f'    {hex_str},')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};')

    content = '\n'.join(lines) + '\n'

    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f'Written {len(entries)} entries to {output_path}')
    else:
        print(content)


def main():
    output_path = None
    args = sys.argv[1:]

    for i, a in enumerate(args):
        if a == '--output' and i + 1 < len(args):
            output_path = args[i + 1]

    entries = generate_table()
    print(f'Generated {len(entries)} Unicode->GB2312 mappings')
    write_c_file(entries, output_path)


if __name__ == '__main__':
    main()
